# Generated by Django 5.0.3 on 2024-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='date_of_donation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_Birth',
            field=models.DateField(default='2000-30-12'),
        ),
    ]
