# Generated by Django 5.0.3 on 2024-03-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0002_blooddonor_date_of_donation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='blood_quantity',
            new_name='blood_quantity_in_pints',
        ),
    ]
